-- =====================================================================
-- 0016_notifications.sql
--
-- In-app notifications. One row per recipient. Rows are generated by DB
-- triggers so every code path (server action, direct SQL, future jobs) emits
-- the same notifications without the app having to remember to.
--
-- What gets generated:
--   task_assigned     -> the assignee (+ admins) when a task is (re)assigned
--   task_completed    -> admins + the project owner when a task goes to done
--   project_completed -> admins + the project owner when a project hits done
--                        (status = 'done' or derived progress reaching 100)
--   user_pending      -> admins when a new user signs up awaiting approval
--
-- The acting user (auth.uid()) is never notified about their own action, and
-- title/body are rendered here so the client needs no joins.
--
-- Realtime is enabled on the table so the bell updates live.
--
-- Idempotent: safe to re-run. Run after 0015.
-- =====================================================================

-- ----- Enum -------------------------------------------------------------

do $$ begin
  create type public.notification_type as enum (
    'task_assigned',
    'task_completed',
    'project_completed',
    'user_pending'
  );
exception when duplicate_object then null; end $$;

-- ----- Table ------------------------------------------------------------

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,   -- recipient
  actor_id uuid references auth.users (id) on delete set null,          -- who triggered it
  type public.notification_type not null,
  title text not null,
  body text,
  project_id uuid references public.projects (id) on delete cascade,
  task_id uuid references public.tasks (id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id)
  where read_at is null;

alter table public.notifications enable row level security;

-- ----- RLS: a user only ever touches their own notifications ------------
-- Inserts come exclusively from SECURITY DEFINER triggers (which bypass RLS),
-- so there is deliberately no insert policy for end users.

drop policy if exists "Users can read their own notifications" on public.notifications;
create policy "Users can read their own notifications"
  on public.notifications for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can update their own notifications" on public.notifications;
create policy "Users can update their own notifications"
  on public.notifications for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "Users can delete their own notifications" on public.notifications;
create policy "Users can delete their own notifications"
  on public.notifications for delete
  to authenticated
  using (user_id = auth.uid());

-- ----- Task trigger: assignment + completion ----------------------------

create or replace function public.tasks_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_nil uuid := '00000000-0000-0000-0000-000000000000';
  v_actor_name text;
  v_project_name text;
  v_assignee_name text;
  v_assignment_changed boolean;
begin
  select coalesce(nullif(trim(full_name), ''), 'Someone')
    into v_actor_name from public.profiles where id = v_actor;
  v_actor_name := coalesce(v_actor_name, 'Someone');
  select name into v_project_name from public.projects where id = new.project_id;
  v_project_name := coalesce(v_project_name, 'a project');

  v_assignment_changed :=
    new.assignee_id is not null
    and (tg_op = 'INSERT' or new.assignee_id is distinct from old.assignee_id);

  -- 1. Tell the assignee they've been assigned (unless they did it themselves).
  if v_assignment_changed and new.assignee_id <> coalesce(v_actor, v_nil) then
    perform public.create_notification(
      new.assignee_id, 'task_assigned',
      'New task assigned to you',
      v_actor_name || ' assigned you "' || new.title || '" in ' || v_project_name,
      new.project_id, new.id, v_actor);
  end if;

  -- 2. Tell admins about the assignment (skip the actor and the assignee, who
  --    are already covered above).
  if v_assignment_changed then
    select coalesce(nullif(trim(full_name), ''), 'A member')
      into v_assignee_name from public.profiles where id = new.assignee_id;
    insert into public.notifications (user_id, actor_id, type, title, body, project_id, task_id)
    select pr.id, v_actor, 'task_assigned',
      'Task assigned',
      coalesce(v_assignee_name, 'A member') || ' was assigned "' || new.title
        || '" in ' || v_project_name,
      new.project_id, new.id
    from public.profiles pr
    where pr.role = 'admin'
      and pr.id <> coalesce(v_actor, v_nil)
      and pr.id <> new.assignee_id;
  end if;

  -- 3. Completion -> admins + the project owner.
  if new.status = 'done'
     and (tg_op = 'INSERT' or old.status is distinct from 'done') then
    insert into public.notifications (user_id, actor_id, type, title, body, project_id, task_id)
    select uid, v_actor, 'task_completed',
      'Task completed',
      v_actor_name || ' completed "' || new.title || '" in ' || v_project_name,
      new.project_id, new.id
    from (
      select pr.id as uid from public.profiles pr where pr.role = 'admin'
      union
      select p.owner_id from public.projects p where p.id = new.project_id
    ) recips
    where uid is not null and uid <> coalesce(v_actor, v_nil);
  end if;

  return new;
end;
$$;

drop trigger if exists tasks_notify on public.tasks;
create trigger tasks_notify
  after insert or update on public.tasks
  for each row execute function public.tasks_notify();

-- ----- Project trigger: completion --------------------------------------

create or replace function public.projects_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_nil uuid := '00000000-0000-0000-0000-000000000000';
begin
  if (new.status = 'done' and old.status is distinct from 'done')
     or (new.progress = 100 and old.progress is distinct from 100) then
    insert into public.notifications (user_id, actor_id, type, title, body, project_id, task_id)
    select uid, v_actor, 'project_completed',
      'Project completed',
      'Project "' || new.name || '" is complete',
      new.id, null
    from (
      select pr.id as uid from public.profiles pr where pr.role = 'admin'
      union
      select new.owner_id
    ) recips
    where uid is not null and uid <> coalesce(v_actor, v_nil);
  end if;
  return new;
end;
$$;

drop trigger if exists projects_notify on public.projects;
create trigger projects_notify
  after update on public.projects
  for each row execute function public.projects_notify();

-- ----- Profile trigger: new user awaiting approval ----------------------

create or replace function public.profiles_notify_pending()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.approved = false then
    insert into public.notifications (user_id, actor_id, type, title, body, project_id, task_id)
    select pr.id, new.id, 'user_pending',
      'New user awaiting approval',
      coalesce(nullif(trim(new.full_name), ''), 'A new user')
        || ' signed up and is waiting to be approved',
      null, null
    from public.profiles pr
    where pr.role = 'admin' and pr.id <> new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_notify_pending on public.profiles;
create trigger profiles_notify_pending
  after insert on public.profiles
  for each row execute function public.profiles_notify_pending();

-- ----- Insert helper (used by the task trigger) -------------------------

create or replace function public.create_notification(
  p_user uuid,
  p_type public.notification_type,
  p_title text,
  p_body text,
  p_project uuid,
  p_task uuid,
  p_actor uuid
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications
    (user_id, actor_id, type, title, body, project_id, task_id)
  values (p_user, p_actor, p_type, p_title, p_body, p_project, p_task);
$$;

-- ----- Realtime ---------------------------------------------------------
-- Add the table to Supabase's realtime publication so the bell streams new
-- rows. Guarded because re-adding an existing member errors.

do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
  when undefined_object then null;  -- publication missing (non-Supabase env)
end $$;
